apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "1080"
    prometheus.io/path: /metrics
    prometheus.io/scrape: "true"
  labels:
    app: sre-instana-exporter
  name: sre-instana-exporter
spec:
  selector:
    name: sre-instana-exporter
  ports:
  - name: instana-port
    port: 1080
    targetPort: 1080
    protocol: TCP